### Login
# @name login
POST {{host}}/auth/login
content-type: application/json

{
  "email": "john@example.com",
  "password": "password123"
}
###

@myAccessToken = {{login.response.body.accessToken}}

### Create Promotion Rule
# @name createPromotionRule
POST {{host}}/promotion-rules
Content-Type: application/json
authorization: Bearer {{myAccessToken}}

{
  "promotionId": "c59ba272-0162-4cf0-96fe-2827bed1d3bd",
  "scope": "category",
  "minQty": 1,
  "minAmount": 100
}

### Get All Promotion Rules
GET {{host}}/promotion-rules
Content-Type: application/json
authorization: Bearer {{myAccessToken}}

### Get All Promotion Rules with Filters
GET {{host}}/promotion-rules?sort=createdAt&order=DESC&page=1&limit=10&promotionId=c59ba272-0162-4cf0-96fe-2827bed1d3bd&scope=product
authorization: Bearer {{myAccessToken}}

### Get Promotion Rules By Promotion Id
GET {{host}}/promotion-rules/by-promotion/c59ba272-0162-4cf0-96fe-2827bed1d3bd
authorization: Bearer {{myAccessToken}}

### Get Promotion Rule By Id
GET {{host}}/promotion-rules/aa7aa029-ddbd-44c0-8616-da3e0fa252a7
authorization: Bearer {{myAccessToken}}

### Update Promotion Rule
PUT {{host}}/promotion-rules/aa7aa029-ddbd-44c0-8616-da3e0fa252a7
Content-Type: application/json
authorization: Bearer {{myAccessToken}}

{
  "scope": "category",
  "minQty": 2,
  "minAmount": 253
}

### Delete Promotion Rule
DELETE {{host}}/promotion-rules/aa7aa029-ddbd-44c0-8616-da3e0fa252a7
authorization: Bearer {{myAccessToken}}