### Login
# @name login
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "password123"
}
###

@myAccessToken = {{login.response.body.accessToken}}

### Create Promotion Rule
# @name createPromotionRule
POST {{host}}/promotion-rules
Content-Type: application/json
authorization: Bearer {{myAccessToken}}

{
  "promotionId": "3e489658-4c47-442b-a9a2-6c5a28f621f3",
  "scope": "product",
  "minQty": 1,
  "minAmount": 100
}

### Get All Promotion Rules
GET {{host}}/promotion-rules
Content-Type: application/json
authorization: Bearer {{myAccessToken}}

### Get All Promotion Rules with Filters
GET {{host}}/promotion-rules?search=min&sort=createdAt&order=DESC&page=1&limit=10&promotionId=62184009-df53-45a8-bca7-e960f83df669&scope=product
authorization: Bearer {{myAccessToken}}

### Get Promotion Rules By Promotion Id
GET {{host}}/promotion-rules/by-promotion/3e489658-4c47-442b-a9a2-6c5a28f621f3
authorization: Bearer {{myAccessToken}}

### Get Promotion Rule By Id
GET {{host}}/promotion-rules/aa7aa029-ddbd-44c0-8616-da3e0fa252a7
authorization: Bearer {{myAccessToken}}

### Update Promotion Rule
PUT {{host}}/promotion-rules/aa7aa029-ddbd-44c0-8616-da3e0fa252a7
Content-Type: application/json
authorization: Bearer {{myAccessToken}}

{
  "scope": "category",
  "minQty": 2,
  "minAmount": 250
}

### Delete Promotion Rule
DELETE {{host}}/promotion-rules/aa7aa029-ddbd-44c0-8616-da3e0fa252a7
authorization: Bearer {{myAccessToken}}