apiVersion: v1
kind: ConfigMap
metadata:
  name: expense-tracker-config
  namespace: expense-tracker
data:
  NODE_ENV: "production"
  PORT: "9009"
  LOG_LEVEL: "info"
  DEFAULT_TIME_ZONE: "Asia/Bangkok"
  # Set if you use OpenTelemetry Collector endpoint
  OTLP_EXPORTER_URL: "http://otel-collector:4318"

