apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker-api
  namespace: expense-tracker
  labels:
    app.kubernetes.io/name: expense-tracker-api
    app.kubernetes.io/part-of: expense-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: expense-tracker-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: expense-tracker-api
        app.kubernetes.io/part-of: expense-tracker
    spec:
      containers:
        - name: api
          # Replace with your image registry and tag
          image: your-registry/expense-tracker-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9009
          env:
            # App config
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: expense-tracker-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: expense-tracker-config
                  key: PORT
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: expense-tracker-config
                  key: LOG_LEVEL
            - name: DEFAULT_TIME_ZONE
              valueFrom:
                configMapKeyRef:
                  name: expense-tracker-config
                  key: DEFAULT_TIME_ZONE
            - name: OTLP_EXPORTER_URL
              valueFrom:
                configMapKeyRef:
                  name: expense-tracker-config
                  key: OTLP_EXPORTER_URL
            # DB config
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: expense-tracker-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: expense-tracker-secrets
                  key: DB_PORT
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: expense-tracker-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: expense-tracker-secrets
                  key: DB_PASSWORD
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: expense-tracker-secrets
                  key: DB_DATABASE
            - name: DB_DIALECT
              value: "postgres"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: expense-tracker-secrets
                  key: JWT_SECRET
            # K8s metadata for logging/telemetry
            - name: SERVICE_NAME
              value: "expense-tracker-api"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: VERSION
              value: "v1"
          readinessProbe:
            httpGet:
              path: /health
              port: 9009
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 9009
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

