apiVersion: v1
kind: Secret
metadata:
  name: expense-tracker-secrets
  namespace: expense-tracker
type: Opaque
stringData:
  # CHANGE THESE in your environment or use your secret manager
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres123"
  DB_DATABASE: "expense_tracker_prod"
  JWT_SECRET: "replace-me-super-secret"

